// Automatically generated by scripts/generate-pwa-version.mjs
export const APP_VERSION = '2026.10.43dcad4';
export const BUILD_ID = '43dcad4';
export const CACHE_STATIC_NAME = 'duopay-static-43dcad4';
export const CACHE_RUNTIME_NAME = 'duopay-runtime-43dcad4';
