// Automatically generated by scripts/generate-pwa-version.mjs
export const APP_VERSION = '2026.10.dafb7c9';
export const BUILD_ID = 'dafb7c9';
export const CACHE_STATIC_NAME = 'duopay-static-dafb7c9';
export const CACHE_RUNTIME_NAME = 'duopay-runtime-dafb7c9';
