// Automatically generated by scripts/generate-pwa-version.mjs
export const APP_VERSION = '2026.10.7eb9708';
export const BUILD_ID = '7eb9708';
export const CACHE_STATIC_NAME = 'duopay-static-7eb9708';
export const CACHE_RUNTIME_NAME = 'duopay-runtime-7eb9708';
